### ISSUE TITLE
Email Confirmation Fails Due to Missing Server-Side Code in Sign-Up Flow

### ISSUE THREAD

**Issue by Harris-A-Khan** [cowboycodr/KianKit#26]
### Description
Once a user signs up for an account, they cannot confirm their email address. The link to the confirmation page does not have any server side code to actually authenticate the user. The deployed version of KianKit does have this, so I suspect the issue only exists because the creator forgot to add that server side component. 

### Steps to Reproduce
1. Run KianKit
2. Enter valid email and password.
3. Click on the "Sign Up" button.
4. Navigate to email confirmation and click the confirmation link. 
5. Observe behavior

### Expected Behavior
The user should be redirected to the desired redirected page or to the home page of the application. 

### Actual Behavior
Nothing happens, but there is an error on the server side of the sveltekit application. 

### Possible Solution
The issue is likely because no server side code and endpoint exists to handle the sign up.

**Comment by cowboycodr** [comment]
Yes. I need to include something about this in my documentation. Essentially, this is something you must configure on Supabase.

I'll spend the next couple of minutes pulling up some documentation on how to do it.

**Comment by Harris-A-Khan** [comment]
Why not add this to the code itself? I think I know what you're talking about, you can turn off the default behavior for user confirmation, but most users would likely want to leave this on, right? It's possible the solution is something else. I created a branch that can handle email confirmation but it would still need some documentation for user set up.

**Comment by cowboycodr** [comment]
Documentation is definitely lacking. I apologize, and I will prioritize doing a better job on this in the future.

KianKit is designed to work with email confirmation as long as SupaBase is configured properly.

First, have you properly configured your site URL on Supabase's dashboard in the auth section of your project?

Example:
![image](https://github.com/user-attachments/assets/0dd6060e-45ce-42d6-935f-3eba710c5954)

Additionally, if you're running into this issue during development as well, you must define redirect URLS (below the section I just screenshotted) for your dev environment (where you're running it locally):

![image](https://github.com/user-attachments/assets/e5f843ca-b0e4-439b-acca-228982e55548)

**Comment by Harris-A-Khan** [comment]
No worries, don't apologize. 

I set up the site URL to be localhost:5173. Some action has to occur on the server side, right? I saw what the email template looks like on your deployed instance and copied that. That didn't work. Are you saying The site URL needs to be kit.fromkian.com for it to work properly? If so, I think it would be better to adopt the official solution provided by Supabase.

**Comment by Harris-A-Khan** [comment]
And I am of course willing to help you with any documentation or anything like that you may need help with

**Comment by cowboycodr** [comment]
The `SITE_URL` must be set to your specific URL and also have "http://localhost:<PORT>/**" while in production. 

My email template on the dashboard looks like this (so it is not hard coded to be related to KianKit or anything):
![image](https://github.com/user-attachments/assets/d0fbc900-e2b9-49b7-9039-f2a7a99b897e)

Can you describe where you're running into this issue? So you're getting the email, correct? Then when you click on the email you're having the problem, right?

> Note: The deployed instance at [kit.fromkian.com](https://kit.fromkian.com) is this exact repository hosted on Vercel

**Comment by Harris-A-Khan** [comment]
I see! I actually didn't even realize there was a confirmation URL variable I could pass in through the email. In the official documentation for setting up Server Side Authentication in Sveltekit, they make you create your own email where the server side code in your application handles confirming the email. I wonder why they don't do it this way.

**Comment by cowboycodr** [comment]
Yea, I wish you could override the email template in the code itself. I've talked to the Supabase founders about creating a one-click deploy button that essentially clones an existing Supabase set up. Vercel has this feature, and it makes setting up boilerplates significantly easier.

Anyways, I'm glad I could help. In the meantime I've started work on documentation.
