### ISSUE TITLE
Improve Sitemap

### ISSUE THREAD

**Issue by jasongitmail** [cowboycodr/KianKit#52]
This looks great. Hopefully templates like these will help the SvelteKit community to grow!

For SEO, it's missing a functioning sitemap and robots.txt. Looks to be [just a placeholder](https://github.com/cowboycodr/KianKit/blob/main/src/routes/sitemap.xml/%2Bserver.js).

I might suggest Super Sitemap: https://github.com/jasongitmail/super-sitemap (I'm the author & searched deeply for a good one before building this.)

Aligns with your values of keeping things [simple in terms of developer experience](https://github.com/jasongitmail/super-sitemap?tab=readme-ov-file#installation):
```ts
// /src/routes/sitemap.xml/+server.ts
import * as sitemap from 'super-sitemap';
import type { RequestHandler } from '@sveltejs/kit';

export const GET: RequestHandler = async () => {
  return await sitemap.response({
    origin: 'https://example.com',
    excludeRoutePatterns: [
      '.*\\(app\\).*', // i.e. routes within a group
    ],
  });
};
```
If you decide to add it, remember to include the `(app)` group within the `excludeRoutePatterns` to omit those from your sitemap, and any others you might want to exclude.

**Comment by cowboycodr** [comment]
Wow man, this is great!

I'll implement later today when I'm at my machine.

**Comment by cowboycodr** [comment]
#53 Implemented here

Thanks for the suggestion, and brilliant library.

**Comment by jasongitmail** [comment]
Nice 🙂 thanks
